-- PostgreSQL Initialization Script
-- Generated by nself build

-- Create database if not exists
SELECT 'CREATE DATABASE "roost_dev"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'roost_dev')\gexec

-- Grant all privileges
GRANT ALL PRIVILEGES ON DATABASE "roost_dev" TO roost;

-- Create MLflow database if MLflow is enabled

-- Connect to the database
\c "roost_dev"

-- Create default schema
CREATE SCHEMA IF NOT EXISTS public;
GRANT ALL ON SCHEMA public TO roost;
GRANT ALL ON ALL TABLES IN SCHEMA public TO roost;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO roost;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO roost;

-- Always create auth schema (required for auth service)
CREATE SCHEMA IF NOT EXISTS auth;
GRANT ALL ON SCHEMA auth TO roost;
GRANT ALL ON ALL TABLES IN SCHEMA auth TO roost;
GRANT ALL ON ALL SEQUENCES IN SCHEMA auth TO roost;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA auth TO roost;

-- Always create storage schema (may be needed later)
CREATE SCHEMA IF NOT EXISTS storage;
GRANT ALL ON SCHEMA storage TO roost;
GRANT ALL ON ALL TABLES IN SCHEMA storage TO roost;
GRANT ALL ON ALL SEQUENCES IN SCHEMA storage TO roost;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA storage TO roost;
