-- Database Schemas
-- Generated by nself build

\c roost_dev

-- Create auth schema if auth is enabled
CREATE SCHEMA IF NOT EXISTS auth;

-- Create storage schema if storage is enabled
CREATE SCHEMA IF NOT EXISTS storage;

-- Create Hasura schema
CREATE SCHEMA IF NOT EXISTS hdb_catalog;

-- Grant permissions
GRANT ALL ON SCHEMA auth TO roost;
GRANT ALL ON SCHEMA storage TO roost;
GRANT ALL ON SCHEMA hdb_catalog TO roost;
