-- Hasura Initialization
-- Generated by nself build

\c roost_dev

-- Create Hasura catalog schema
CREATE SCHEMA IF NOT EXISTS hdb_catalog;

-- Create Hasura views schema
CREATE SCHEMA IF NOT EXISTS hdb_views;

-- Grant permissions
GRANT ALL ON SCHEMA hdb_catalog TO roost;
GRANT ALL ON SCHEMA hdb_views TO roost;
GRANT ALL ON ALL TABLES IN SCHEMA hdb_catalog TO roost;
GRANT ALL ON ALL SEQUENCES IN SCHEMA hdb_catalog TO roost;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA hdb_catalog TO roost;
